[project]
name = "jobhiringsystem"
version = "0.1.0"
requires-python = ">=3.14"

dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn>=0.52.4",
]


[dependency-groups]
dev = [
    "import-linter>=2.14",
    "pyright>=1.1.411",
]


[tool.pyright]
pythonVersion = "3.14"
typeCheckingMode = "strict"

include = [
    "src",
]

extraPaths = ["src"]

exclude = [
    "**/__pycache__",
    ".venv",
    "alembic/versions",
]

venvPath = "."
venv = ".venv"

reportMissingTypeStubs = false
reportUnnecessaryTypeIgnoreComment = "warning"

[tool.importlinter]

root_packages = [
    "bootstrap",
    "presentation",
    "infrastructure",
    "application",
    "domain",
]

[[tool.importlinter.contracts]]
name = "Clean Architecture"
type = "layers"

layers = [
    "bootstrap",
    "presentation | infrastructure",
    "application",
    "domain",
]
