"""make profile_id unique

Revision ID: bc7aae6b174b
Revises: dc8264c43357
Create Date: 2026-09-05 17:28:07.442138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7aae6b174b'
down_revision: Union[str, Sequence[str], None] = 'dc8264c43357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attached_resumes', ['applicant_profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attached_resumes', type_='unique')
    # ### end Alembic commands ###
