"""add timestamp class to jobs

Revision ID: 5e218336c6e5
Revises: 7f2c0b3f4a1d
Create Date: 2026-09-09 13:33:02.721979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e218336c6e5'
down_revision: Union[str, Sequence[str], None] = '7f2c0b3f4a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_postings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'updated_at')
    op.drop_column('job_postings', 'created_at')
    # ### end Alembic commands ###
